export enum ConteoProveedorEstadoEnvioType {

  RECOLECCION = 'RECOLECCION',
  CAMINO = 'CAMINO',
  DEVUELTO = 'DEVUELTO',
  ENTREGADO = 'ENTREGADO',
  CANCELADO = 'CANCELADO',
  PENDIENTE = 'PENDIENTE'

}
